<a href="https://colab.research.google.com/github/Khushitz/MACHINE-LEARNING/blob/MACHINE-LEARNING/Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**What is Cross Validation?**

Cross Validation is a technique used to:

Check how well your model will perform on unseen data.

Instead of splitting data only once into train & test…

We test the model multiple times on different splits.

This gives a more reliable performance estimate.

SOMETIMES TRAIN_TEST_SPLIT METHOD DOES NOT WORKS WELL

LIKE WHEN THE DATA IS SPLIT INTO LET'S SAY 0.3 TESTING SO IF A CHILD HAS PREPARED 70% FOR ALGEBRA AND THE REST 30% CAME FROM CALCULUS SO THAT WOULD NOT GIVE ACCURATE RESULTS HENCE THAT'S WHY SOMETIMES THIS BECOMES INACURATE.


**K-FOLD VALIDATION**
if there are dataset of 100 samples fold it into 5 samples and then perform steps like 1 fold use for test other 4 for training note down the scores then do the same but for 2nd fold note down the scores again and keep on doing this then later take down the averages

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size =0.3)

In [6]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

In [7]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9888888888888889

In [8]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9592592592592593

In [9]:
from sklearn.model_selection import KFold

data = [1,2,3,4,5,6,7,8,9]

kf = KFold(n_splits=3, shuffle=True, random_state=42)

for train_index, test_index in kf.split(data):
    print("Train indices:", train_index)
    print("Test indices:", test_index)
    print()


Train indices: [0 2 3 4 6 8]
Test indices: [1 5 7]

Train indices: [1 3 4 5 6 7]
Test indices: [0 2 8]

Train indices: [0 1 2 5 7 8]
Test indices: [3 4 6]



In [10]:
def get_score(model, x_train,x_test,y_train,y_test):
  model.fit(x_train,y_train)
  return model.score(x_test,y_test)

In [14]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9703703703703703

In [15]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9907407407407407

In [17]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [21]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):

    x_train = digits.data[train_index]
    x_test  = digits.data[test_index]
    y_train = digits.target[train_index]
    y_test  = digits.target[test_index]

    scores_l.append(get_score(LogisticRegression(), x_train, x_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), x_train, x_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [22]:
scores_l

[0.9649415692821369, 0.9649415692821369, 0.9532554257095158]

In [23]:
scores_svm

[0.986644407345576, 0.988313856427379, 0.986644407345576]

In [24]:
scores_rf

[0.9699499165275459, 0.9616026711185309, 0.9766277128547579]

In [25]:
from sklearn.model_selection import cross_val_score

In [26]:
cross_val_score(LogisticRegression(), digits.data,digits.target)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [27]:
cross_val_score(SVC(), digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [31]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.92777778, 0.89444444, 0.94707521, 0.97493036, 0.91643454])